name: build
on:
  push:
    branches-ignore:
      - "main"
      - "develop"
    paths-ignore:
      - "functions/**"

jobs:
  build-nextjs:
    name: Build Next.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install npm v7
        run: npm install -g npm@7
      - run: npm ci
      - run: npm run build
