name: build
on:
  push:
    branches-ignore:
      - "main"
      - "develop"
    paths:
      - "functions/**"

jobs:
  build-functions:
    name: Build Firebase Cloud Functions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install npm v7
        run: npm install -g npm@7
      - run: npm ci
      - run: npm run build
