name: Unit test
on: push

jobs:
  test-firestore:
    name: Test Firestore security rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install npm v7
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Run Firestore unit tests
        run: npx -y firebase-tools emulators:exec --only firestore "npm run test:unit:firestore"
