name: Unit test
on:
  push:
    paths:
      - ".firebase/firestore.rules"

jobs:
  test-firestore:
    name: Unit test Firestore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
          node-version: "12"

      - name: Install npm v7
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Run Firestore unit tests
        uses: w9jds/firebase-action@master
        with:
          args: emulators:exec --only firestore "npm run test:unit:firestore"
