name: Unit test components
on: push

jobs:
  test-components:
    name: Test components with Jest and Enzyme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install npm v7
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Run component unit tests
        run: npm run test:unit:components
